COLUMNS:
  customer_id: int64
  credit_lines_outstanding: int64
  loan_amt_outstanding: float64
  total_debt_outstanding: float64
  income: float64
  years_employed: int64
  fico_score: int64
  default: int64



TARGET_COLUMNS:
  name: default


NEW_FEATURES:
  debt_to_income: [total_debt_outstanding, income] #total_debt_outstanding/income
  payment_to_income: [loan_amt_outstanding, income] #loan_amt_outstanding/income


DROP_FEATURES:
  customer_id: int64
  total_debt_outstanding: float64
  loan_amt_outstanding: float64
  income: float64
